### PR TITLE
Ntuples for AK8 bb and subjets

### PR DESCRIPTION
**Pull request by dmajumder**
This PR has the following changes:
- jet flavour: introducing cc category. Distinguishing between bb and gluon->bb, cc and gluon->cc categories. 
- workflow DeepNtuplizerAK8.py which creates two trees: one storing only subjets (without reference to AK8 jets), and the other storing AK8 jets. 
- the qgtagger InputTag is now a configurable (needed for the above workflow).

### CODE REVIEW

**Comment by mverzett** [comment]
Hi, did you test both the AK8 and the AK4 ntuplizers to run and give meaningful results? Also, you should take care of making a similar PR to DeepJet to merge the new categories you introduced for the sake of AK4 training

**Comment by dmajumder** [comment]
@mverzett yes, I ran the DeepNtuplizer.py cfg using a bulk grav sample and the flavour break-up seems along the same lines as the AK8 jets.

I'll  start having a look at the DeepJet code. May be discuss Monday at the meeting.

**Comment by mverzett** [comment]
@dmajumder , sorry, I completely lost track of this.

**Comment by dmajumder** [comment]
@mverzett thanks. I'll get on with the rest of the stuff.

**Pull request merged**
