### PR TITLE
added installation tools

### PR DESCRIPTION
**Pull request by jkiesele**
Only additional files, no conflicts expected

### CODE REVIEW

**Comment by jkiesele** [comment]
The structure of the ntuplizer needed to be changed for mass production.
I did not commit these changes to the same file to avoid even more merge conflicts.
In the end it is mostly about moving things from the constructor to the beginJob() function and using the TFileService. It needs to be added as a member and used to create the tree in the beginJob() function. Also all branches should be stored there.

Also, the config file needed to be changed. It is now not located in "test" anymore, but in a more suitable place, the "production" directory.

**Comment by mverzett** [comment]
Hi, if the files under installation/ are meant to work on our private machines I'd rather have them in another repository. Also, the README breaks at "run", maybe you forgot to commit everything. What do you think?

**Comment by jkiesele** [comment]
Hi,

that the readme breaks is certainly a commit problem - fixed now. 
After the discussion from last time I was under the impression we should have it in the same so I committed in there.
But you are right, it doesn’t really belong there. I am happy with putting it in any other repo.

Cheers,
Jan

**Comment by jkiesele** [comment]
Hi Mauro,

I am trying to merge, but encounter the following error, when I try to push to the master:

remote: Permission to CMSDeepFlavour/DeepNTuples.git denied to jkiesele.

Is something wrong with the permissions?

Cheers,
Jan

**Comment by mverzett** [comment]
hmmm, that's strange, especially given you should be pushing to **your** remote. Can you give me the exact commands you issue? And the output of 
```
git branch
git remote -v
```
thanks

**Pull request merged**
